name: Run tests on any Push event
# Запуск при любом push евенте в любой ветке, за исключением релизных тэгов.
# Они будт тестироваться перед сборкой
on:
  push:
    tags:
      - '!refs/tags/*'
    branches:
      - '*'
jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      # Чекаутим код
      - uses: actions/checkout@master

      # Устанавливаем python нужной версии
      - name: Set up Python
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Set up Chrome
      - uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable

      - name: Setup Chromedriver
      - uses: nanasess/setup-chromedriver@master

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest

      - name: Tests report
        run: coverage report
